# Generated by Django 4.2.23 on 2025-08-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_colores_producto_tallas_stockproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_producto_categoria_alter_itempedido_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('talla', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('motivo', models.CharField(help_text='Motivo de la entrada (ej: llegada de proveedor, ajuste, devolución, etc.)', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_inventario', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
