# Generated by Django 4.2.23 on 2025-07-25 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL amigable (ej: taller-tejido-basico)', max_length=200, unique=True)),
                ('descripcion_corta', models.TextField(blank=True, help_text='Breve resumen del servicio')),
                ('descripcion_larga', models.TextField()),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Precio estimado o desde', max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('disponible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField(help_text='Detalles de la solicitud o pregunta')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='servicios.servicio')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Servicio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
