# Generated by Django 4.2.23 on 2025-08-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_adicional', models.TextField(blank=True, help_text='Dirección, ciudad, o cualquier otro detalle de contacto.')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o preguntas adicionales del inscrito.')),
                ('como_supo_del_curso', models.CharField(blank=True, help_text='¿De dónde supiste del curso?', max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='servicios.servicio')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones a Cursos',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
