# Generated by Django 4.2.23 on 2025-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_fondo',
            field=models.CharField(default='fondo.png', help_text='Imagen de fondo de la tarjeta (elige una de las imágenes del proyecto)', max_length=64),
        ),
    ]
