# Generated by Django 4.2.23 on 2025-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categoria_imagen_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_3d',
            field=models.ImageField(blank=True, help_text='Imagen 3D del producto para la categoría', null=True, upload_to='productos_3d/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_fondo',
            field=models.CharField(choices=[('fondo.png', 'Fondo 1'), ('fondo1.png', 'Fondo 2'), ('fondo3.png', 'Fondo 3'), ('fondo4.png', 'Fondo 4'), ('mujer.png', 'Mujer'), ('mujer1.png', 'Mujer 2'), ('hombre.png', 'Hombre'), ('hombre1.png', 'Hombre 2'), ('servicios.png', 'Servicios'), ('imagen1defondo.pngx', 'tarjetas')], default='fondo.png', help_text='Imagen de fondo de la tarjeta (elige una de las imágenes del proyecto)', max_length=64),
        ),
    ]
