# Generated by Django 4.2.23 on 2025-08-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_imagen_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen_3d',
        ),
    ]
