# Generated by Django 4.2.23 on 2025-08-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_categoria_imagen_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_fondo',
            field=models.CharField(choices=[('fondo_zapatos_rosados.png', 'Zapatos Rosados'), ('tarjeta1.png', 'Tarjeta 1'), ('tarjeta2.png', 'Tarjeta 2'), ('tarjeta3.png', 'Tarjeta 3')], default='fondo_zapatos_rosados.png', help_text='Imagen de fondo de la tarjeta del producto (elige una de las imágenes del proyecto)', max_length=64),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_fondo',
            field=models.CharField(choices=[('imagen1defondo.png', 'tarjetas'), ('tarjeta1.png', 'tarjeta1'), ('tarjeta2.png', 'tarjeta2'), ('tarjeta3.png', 'tarjeta3')], default='fondo.png', help_text='Imagen de fondo de la tarjeta (elige una de las imágenes del proyecto)', max_length=64),
        ),
    ]
