# Generated by Django 4.2.23 on 2025-08-26 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0008_producto_imagen_fondo_alter_categoria_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_fondo',
            field=models.CharField(choices=[('fondo_zapatos_rosados.png', 'Zapatos Rosados'), ('tarjeta4.png', 'Tarjeta 4'), ('tarjeta5.png', 'Tarjeta 5'), ('tarjeta7.png', 'Tarjeta 7'), ('tarjeta8.png', 'Tarjeta 8')], default='fondo_zapatos_rosados.png', help_text='Imagen de fondo de la tarjeta del producto (elige una de las imágenes del proyecto)', max_length=64),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
