# Generated by Django 4.2.23 on 2025-08-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_imagen_fondo_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
