# Generated by Django 4.2.23 on 2025-08-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_favorito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.CharField(blank=True, help_text='Ejemplo: Rojo, Azul, Verde', max_length=120),
        ),
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, help_text='Ejemplo: 36,37,38,39', max_length=120),
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_detalle', to='productos.producto')),
            ],
            options={
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
    ]
