# Generated by Django 4.2.23 on 2025-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_salida_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
